In [1]:
import numpy as np
from eig.battleship import Ship, BattleshipHypothesis, Parser, Executor
from eig import compute_eig_fast
from eig.battleship.program import ProgramSyntaxError

In [23]:
# define a board using BattleshipHypothesis
ships = [
    Ship(ship_label=1, topleft=(0, 0), size=2, orientation='V'),
    Ship(ship_label=2, topleft=(1, 2), size=2, orientation='V')
]
hypothesis = BattleshipHypothesis(grid_size=3, ships=ships)
print(hypothesis.board)

# parse and execute the program
# question = Parser.parse("(bottomright (coloredTiles Red))")
# question = Parser.parse("(orient Red)")
# question = Parser.parse("(color 2-1)")
# question = Parser.parse("(color A-3)")
question = Parser.parse("(not (== (color A-3) Water))")

executor = Executor(question)
executor.execute(hypothesis)

[[1 0 0]
 [1 0 2]
 [0 0 2]]


9

In [3]:
Parser.parse("(orient Red)")

In [4]:
executor.execute(hypothesis)

(2, 2)

In [4]:
hypothesis.board

array([[1, 0, 0],
       [1, 0, 2],
       [0, 0, 2]])

In [5]:
h = hypothesis.board.copy()
h[0][2] = -1
h[2][2] = -1
h

array([[ 1,  0, -1],
       [ 1,  0,  2],
       [ 0,  0, -1]])

In [6]:
program = "(bottomright (coloredTiles Red))"
board = h

score = compute_eig_fast(program, board, grid_size=3, ship_labels=[1, 2], ship_sizes=[2, 2], orientations=['V', 'H'])

In [7]:
score

0.9182958340544896